# Generated by Django 5.2.5 on 2026-07-25 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0003_attestedfcmdevice_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(choices=[('polkadot', 'Polkadot'), ('solana', 'Solana')], max_length=32, verbose_name='Chain')),
                ('address', models.TextField(verbose_name='Wallet address')),
                ('verified', models.BooleanField(default=False, verbose_name='Ownership verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Linked at')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='ApiApp.attestedfcmdevice', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Wallet link',
                'verbose_name_plural': 'Wallet links',
                'indexes': [models.Index(fields=['chain', 'address'], name='ApiApp_wall_chain_ee5cdb_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'chain', 'address'), name='uniq_device_chain_address')],
            },
        ),
    ]
